# Generated by Django 2.2 on 2023-01-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
