# Generated by Django 2.2 on 2023-01-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0004_auto_20230105_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
