# Generated by Django 2.2 on 2023-01-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0008_auto_20230106_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_user',
            new_name='ids',
        ),
    ]
