# Generated by Django 2.2 on 2023-01-06 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0009_auto_20230106_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendersname', models.CharField(blank=True, max_length=40)),
                ('receiversname', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(max_length=400)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='facebookapp.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='facebookapp.Profile')),
            ],
        ),
    ]
