# Generated by Django 2.2 on 2023-01-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0011_auto_20230107_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='particularpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='facebookapp.Post'),
            preserve_default=False,
        ),
    ]
