# Generated by Django 2.2 on 2023-01-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0012_likepost_particularpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='particularpost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='facebookapp.Post'),
        ),
    ]
