# Generated by Django 2.2 on 2023-01-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0013_auto_20230107_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='particularpost',
        ),
    ]
