# Generated by Django 2.2 on 2023-01-08 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebookapp', '0014_remove_likepost_particularpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='likedusers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likedby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
