# Generated by Django 2.2 on 2023-01-08 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebookapp', '0018_remove_profile_friendslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friendnames',
            field=models.ManyToManyField(blank=True, related_name='friendinlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
