# Generated by Django 2.2 on 2023-01-09 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebookapp', '0019_profile_friendnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followedby',
            field=models.ManyToManyField(blank=True, related_name='followerslist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followinglist', to=settings.AUTH_USER_MODEL),
        ),
    ]
