# Generated by Django 2.2 on 2023-01-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0020_auto_20230109_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentedby',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='commentedby', to='facebookapp.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postedby',
            field=models.ForeignKey(default=888, on_delete=django.db.models.deletion.CASCADE, related_name='postedby', to='facebookapp.Profile'),
            preserve_default=False,
        ),
    ]
