# Generated by Django 2.2 on 2023-01-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0021_auto_20230109_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(blank=True, default='profile_images/coverimg.jpg', upload_to='profile_images'),
        ),
    ]
